# Generated by Django 5.2 on 2025-04-20 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Profession Categories',
            },
        ),
        migrations.AddField(
            model_name='alumniskill',
            name='proficiency_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert'), (5, 'Master')], default=3),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, choices=[('technical', 'Technical Skill'), ('soft', 'Soft Skill'), ('language', 'Language'), ('certification', 'Certification'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AlumniProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_role', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.professioncategory')),
            ],
            options={
                'unique_together': {('alumni', 'category', 'specific_role')},
            },
        ),
    ]
